version: '3.7'

services:
  tcm-server-db:
    image: "mongo"
    container_name: 'tcm-server-db'
    environment:
      - MONGO_INITDB_DATABASE=tcmdb
      - MONGO_INITDB_ROOT_USERNAME=tcmrootuser
      - MONGO_INITDB_ROOT_PASSWORD=tcmrootpass
    ports:
      - '27017-27019:27017-27019'
    volumes:
      - ./mongo/tcm-server-db-init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
      - tcm-server-db-volume:/data/db

volumes:
  tcm-server-db-volume:
